# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faiss_server.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='faiss_server.proto',
  package='faiss_server',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12\x66\x61iss_server.proto\x12\x0c\x66\x61iss_server\"\xa3\x01\n\rSearchRequest\x12\x12\n\nindex_name\x18\x01 \x01(\t\x12)\n\x06vector\x18\x02 \x01(\x0b\x32\x19.faiss_server.FloatVector\x12\x0b\n\x03\x61\x64\x64\x18\x03 \x01(\x08\x12\x0c\n\x04topn\x18\x04 \x01(\r\x12#\n\x02id\x18\x05 \x01(\x0b\x32\x17.faiss_server.IntVector\x12\x13\n\x0b\x61\x64\x64_with_id\x18\x06 \x01(\x08\"h\n\x0bSearchReply\x12$\n\x01\x44\x18\x01 \x01(\x0b\x32\x19.faiss_server.FloatMatrix\x12\"\n\x01I\x18\x02 \x01(\x0b\x32\x17.faiss_server.IntMatrix\x12\x0f\n\x07success\x18\x03 \x01(\x08\"\x85\x01\n\nAddRequest\x12\x12\n\nindex_name\x18\x01 \x01(\t\x12)\n\x06vector\x18\x02 \x01(\x0b\x32\x19.faiss_server.FloatVector\x12\x13\n\x0b\x61\x64\x64_with_id\x18\x03 \x01(\x08\x12#\n\x02id\x18\x04 \x01(\x0b\x32\x17.faiss_server.IntVector\"\x1b\n\x08\x41\x64\x64Reply\x12\x0f\n\x07success\x18\x01 \x01(\x08\"%\n\x0fGetCountRequest\x12\x12\n\nindex_name\x18\x01 \x01(\t\"\x1e\n\rGetCountReply\x12\r\n\x05\x63ount\x18\x01 \x01(\r\"5\n\tIntMatrix\x12(\n\x07imatrix\x18\x01 \x03(\x0b\x32\x17.faiss_server.IntVector\"\x19\n\tIntVector\x12\x0c\n\x04ivec\x18\x01 \x03(\r\"9\n\x0b\x46loatMatrix\x12*\n\x07\x66matrix\x18\x01 \x03(\x0b\x32\x19.faiss_server.FloatVector\"\x1b\n\x0b\x46loatVector\x12\x0c\n\x04\x66vec\x18\x01 \x03(\x02\x32\xd7\x01\n\x0b\x46\x61issServer\x12\x42\n\x06search\x12\x1b.faiss_server.SearchRequest\x1a\x19.faiss_server.SearchReply\"\x00\x12\x39\n\x03\x61\x64\x64\x12\x18.faiss_server.AddRequest\x1a\x16.faiss_server.AddReply\"\x00\x12I\n\tget_count\x12\x1d.faiss_server.GetCountRequest\x1a\x1b.faiss_server.GetCountReply\"\x00\x62\x06proto3'
)




_SEARCHREQUEST = _descriptor.Descriptor(
  name='SearchRequest',
  full_name='faiss_server.SearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index_name', full_name='faiss_server.SearchRequest.index_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vector', full_name='faiss_server.SearchRequest.vector', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='add', full_name='faiss_server.SearchRequest.add', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topn', full_name='faiss_server.SearchRequest.topn', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='faiss_server.SearchRequest.id', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='add_with_id', full_name='faiss_server.SearchRequest.add_with_id', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=200,
)


_SEARCHREPLY = _descriptor.Descriptor(
  name='SearchReply',
  full_name='faiss_server.SearchReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='D', full_name='faiss_server.SearchReply.D', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='I', full_name='faiss_server.SearchReply.I', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='success', full_name='faiss_server.SearchReply.success', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=306,
)


_ADDREQUEST = _descriptor.Descriptor(
  name='AddRequest',
  full_name='faiss_server.AddRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index_name', full_name='faiss_server.AddRequest.index_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vector', full_name='faiss_server.AddRequest.vector', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='add_with_id', full_name='faiss_server.AddRequest.add_with_id', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='faiss_server.AddRequest.id', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=442,
)


_ADDREPLY = _descriptor.Descriptor(
  name='AddReply',
  full_name='faiss_server.AddReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='faiss_server.AddReply.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=444,
  serialized_end=471,
)


_GETCOUNTREQUEST = _descriptor.Descriptor(
  name='GetCountRequest',
  full_name='faiss_server.GetCountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index_name', full_name='faiss_server.GetCountRequest.index_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=473,
  serialized_end=510,
)


_GETCOUNTREPLY = _descriptor.Descriptor(
  name='GetCountReply',
  full_name='faiss_server.GetCountReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='faiss_server.GetCountReply.count', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=512,
  serialized_end=542,
)


_INTMATRIX = _descriptor.Descriptor(
  name='IntMatrix',
  full_name='faiss_server.IntMatrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imatrix', full_name='faiss_server.IntMatrix.imatrix', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=544,
  serialized_end=597,
)


_INTVECTOR = _descriptor.Descriptor(
  name='IntVector',
  full_name='faiss_server.IntVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ivec', full_name='faiss_server.IntVector.ivec', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=599,
  serialized_end=624,
)


_FLOATMATRIX = _descriptor.Descriptor(
  name='FloatMatrix',
  full_name='faiss_server.FloatMatrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fmatrix', full_name='faiss_server.FloatMatrix.fmatrix', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=626,
  serialized_end=683,
)


_FLOATVECTOR = _descriptor.Descriptor(
  name='FloatVector',
  full_name='faiss_server.FloatVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fvec', full_name='faiss_server.FloatVector.fvec', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=685,
  serialized_end=712,
)

_SEARCHREQUEST.fields_by_name['vector'].message_type = _FLOATVECTOR
_SEARCHREQUEST.fields_by_name['id'].message_type = _INTVECTOR
_SEARCHREPLY.fields_by_name['D'].message_type = _FLOATMATRIX
_SEARCHREPLY.fields_by_name['I'].message_type = _INTMATRIX
_ADDREQUEST.fields_by_name['vector'].message_type = _FLOATVECTOR
_ADDREQUEST.fields_by_name['id'].message_type = _INTVECTOR
_INTMATRIX.fields_by_name['imatrix'].message_type = _INTVECTOR
_FLOATMATRIX.fields_by_name['fmatrix'].message_type = _FLOATVECTOR
DESCRIPTOR.message_types_by_name['SearchRequest'] = _SEARCHREQUEST
DESCRIPTOR.message_types_by_name['SearchReply'] = _SEARCHREPLY
DESCRIPTOR.message_types_by_name['AddRequest'] = _ADDREQUEST
DESCRIPTOR.message_types_by_name['AddReply'] = _ADDREPLY
DESCRIPTOR.message_types_by_name['GetCountRequest'] = _GETCOUNTREQUEST
DESCRIPTOR.message_types_by_name['GetCountReply'] = _GETCOUNTREPLY
DESCRIPTOR.message_types_by_name['IntMatrix'] = _INTMATRIX
DESCRIPTOR.message_types_by_name['IntVector'] = _INTVECTOR
DESCRIPTOR.message_types_by_name['FloatMatrix'] = _FLOATMATRIX
DESCRIPTOR.message_types_by_name['FloatVector'] = _FLOATVECTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SearchRequest = _reflection.GeneratedProtocolMessageType('SearchRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHREQUEST,
  '__module__' : 'faiss_server_pb2'
  # @@protoc_insertion_point(class_scope:faiss_server.SearchRequest)
  })
_sym_db.RegisterMessage(SearchRequest)

SearchReply = _reflection.GeneratedProtocolMessageType('SearchReply', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHREPLY,
  '__module__' : 'faiss_server_pb2'
  # @@protoc_insertion_point(class_scope:faiss_server.SearchReply)
  })
_sym_db.RegisterMessage(SearchReply)

AddRequest = _reflection.GeneratedProtocolMessageType('AddRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDREQUEST,
  '__module__' : 'faiss_server_pb2'
  # @@protoc_insertion_point(class_scope:faiss_server.AddRequest)
  })
_sym_db.RegisterMessage(AddRequest)

AddReply = _reflection.GeneratedProtocolMessageType('AddReply', (_message.Message,), {
  'DESCRIPTOR' : _ADDREPLY,
  '__module__' : 'faiss_server_pb2'
  # @@protoc_insertion_point(class_scope:faiss_server.AddReply)
  })
_sym_db.RegisterMessage(AddReply)

GetCountRequest = _reflection.GeneratedProtocolMessageType('GetCountRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETCOUNTREQUEST,
  '__module__' : 'faiss_server_pb2'
  # @@protoc_insertion_point(class_scope:faiss_server.GetCountRequest)
  })
_sym_db.RegisterMessage(GetCountRequest)

GetCountReply = _reflection.GeneratedProtocolMessageType('GetCountReply', (_message.Message,), {
  'DESCRIPTOR' : _GETCOUNTREPLY,
  '__module__' : 'faiss_server_pb2'
  # @@protoc_insertion_point(class_scope:faiss_server.GetCountReply)
  })
_sym_db.RegisterMessage(GetCountReply)

IntMatrix = _reflection.GeneratedProtocolMessageType('IntMatrix', (_message.Message,), {
  'DESCRIPTOR' : _INTMATRIX,
  '__module__' : 'faiss_server_pb2'
  # @@protoc_insertion_point(class_scope:faiss_server.IntMatrix)
  })
_sym_db.RegisterMessage(IntMatrix)

IntVector = _reflection.GeneratedProtocolMessageType('IntVector', (_message.Message,), {
  'DESCRIPTOR' : _INTVECTOR,
  '__module__' : 'faiss_server_pb2'
  # @@protoc_insertion_point(class_scope:faiss_server.IntVector)
  })
_sym_db.RegisterMessage(IntVector)

FloatMatrix = _reflection.GeneratedProtocolMessageType('FloatMatrix', (_message.Message,), {
  'DESCRIPTOR' : _FLOATMATRIX,
  '__module__' : 'faiss_server_pb2'
  # @@protoc_insertion_point(class_scope:faiss_server.FloatMatrix)
  })
_sym_db.RegisterMessage(FloatMatrix)

FloatVector = _reflection.GeneratedProtocolMessageType('FloatVector', (_message.Message,), {
  'DESCRIPTOR' : _FLOATVECTOR,
  '__module__' : 'faiss_server_pb2'
  # @@protoc_insertion_point(class_scope:faiss_server.FloatVector)
  })
_sym_db.RegisterMessage(FloatVector)



_FAISSSERVER = _descriptor.ServiceDescriptor(
  name='FaissServer',
  full_name='faiss_server.FaissServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=715,
  serialized_end=930,
  methods=[
  _descriptor.MethodDescriptor(
    name='search',
    full_name='faiss_server.FaissServer.search',
    index=0,
    containing_service=None,
    input_type=_SEARCHREQUEST,
    output_type=_SEARCHREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='add',
    full_name='faiss_server.FaissServer.add',
    index=1,
    containing_service=None,
    input_type=_ADDREQUEST,
    output_type=_ADDREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_count',
    full_name='faiss_server.FaissServer.get_count',
    index=2,
    containing_service=None,
    input_type=_GETCOUNTREQUEST,
    output_type=_GETCOUNTREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FAISSSERVER)

DESCRIPTOR.services_by_name['FaissServer'] = _FAISSSERVER

# @@protoc_insertion_point(module_scope)
